language: java
cache:
  apt: true
  directories:
  - "$HOME/octave"
env:
  global:
  - OCTAVE=octave
before_install:
- travis_retry sudo apt-get -y -qq update
- travis_retry sudo apt-get install -y -qq software-properties-common python-software-properties
- travis_retry sudo apt-add-repository -y ppa:octave/stable
- travis_retry sudo apt-get -y -qq update
- travis_retry sudo apt-get install -y wget
- travis_retry sudo apt-get -y -qq install octave liboctave-dev octave-pkg-dev
- travis_retry wget http://sourceforge.net/projects/octave/files/Octave%20Forge%20Packages/Individual%20Package%20Releases/struct-1.0.14.tar.gz -P /home/travis/octave
- travis_retry wget http://sourceforge.net/projects/octave/files/Octave%20Forge%20Packages/Individual%20Package%20Releases/optim-1.5.2.tar.gz -P /home/travis/octave
- travis_retry wget https://sourceforge.net/projects/octave/files/Octave%20Forge%20Packages/Individual%20Package%20Releases/io-2.4.10.tar.gz -P /home/travis/octave
- travis_retry wget http://sourceforge.net/projects/octave/files/Octave%20Forge%20Packages/Individual%20Package%20Releases/statistics-1.3.0.tar.gz -P /home/travis/octave
- travis_retry wget http://sourceforge.net/projects/octave/files/Octave%20Forge%20Packages/Individual%20Package%20Releases/image-2.6.1.tar.gz -P /home/travis/octave
- make -C External/MOcov install
- pip install --user awscli
- mkdir -p ~/$TRAVIS_BUILD_NUMBER
- aws s3 ls s3://qmrlab
- aws s3 sync s3://qmrlab/$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER
- aws s3 ls s3://qmrlab
- aws s3 ls s3://qmrlab/$TRAVIS_BUILD_NUMBER
- ls ~/$TRAVIS_BUILD_NUMBER
jobs:
  include:
  - stage: Test
    script: travis_wait 30 octave --no-gui --eval "bootstrapTest;cd('/home/travis/build/neuropoly/qMRLab/Test/MoxUnitCompatible/quickMoxTests');res=moxunit_runtests('-recursive','-with_coverage','-cover','/home/travis/build/neuropoly/qMRLab/src','-cover_json_file','coverage_quickMoxTests.json');exit(~res);";cp /home/travis/build/neuropoly/qMRLab/Test/MoxUnitCompatible/quickMoxTests/coverage_quickMoxTests.json ~/$TRAVIS_BUILD_NUMBER/;ls ~/$TRAVIS_BUILD_NUMBER/;ls s3://qmrlab/$TRAVIS_BUILD_NUMBER
  - stage: Test
    script: travis_wait 30 octave --no-gui --eval "bootstrapTest;cd('/home/travis/build/neuropoly/qMRLab/Test/MoxUnitCompatible');res=moxunit_runtests('BatchExample_test.m','-with_coverage','-cover','/home/travis/build/neuropoly/qMRLab/src','-cover_json_file','coverage_BatchExample.json');exit(~res);";cp /home/travis/build/neuropoly/qMRLab/Test/MoxUnitCompatible/coverage_BatchExample.json ~/$TRAVIS_BUILD_NUMBER/;ls ~/$TRAVIS_BUILD_NUMBER/;ls s3://qmrlab/$TRAVIS_BUILD_NUMBER
  - stage: Test
    script: travis_wait 30 octave --no-gui --eval "bootstrapTest;cd('/home/travis/build/neuropoly/qMRLab/Test/MoxUnitCompatible');res=moxunit_runtests('SimTest_charmed.m','-with_coverage','-cover','/home/travis/build/neuropoly/qMRLab/src','-cover_json_file','coverage_SimTest_charmed.json');exit(~res);"
  - stage: Test
    script: travis_wait 30 octave --no-gui --eval "bootstrapTest;cd('/home/travis/build/neuropoly/qMRLab/Test/MoxUnitCompatible');res=moxunit_runtests('SimTest_dti.m','-with_coverage','-cover','/home/travis/build/neuropoly/qMRLab/src','-cover_json_file','coverage_SimTest_dti.json');exit(~res);"
  - stage: Test
    script: travis_wait 30 octave --no-gui --eval "bootstrapTest;cd('/home/travis/build/neuropoly/qMRLab/Test/MoxUnitCompatible');res=moxunit_runtests('SimTest_noddi.m','-with_coverage','-cover','/home/travis/build/neuropoly/qMRLab/src','-cover_json_file','coverage_SimTest_noddi.json');exit(~res);"
  - stage: Test
    script: travis_wait 30 octave --no-gui --eval "bootstrapTest;cd('/home/travis/build/neuropoly/qMRLab/Test/MoxUnitCompatible');res=moxunit_runtests('SimTest_qmt_bssfp.m');exit(~res);"
  - stage: Test
    script: travis_wait 30 octave --no-gui --eval "bootstrapTest;cd('/home/travis/build/neuropoly/qMRLab/Test/MoxUnitCompatible');res=moxunit_runtests('SimTest_qmt_sirfse.m','-with_coverage','-cover','/home/travis/build/neuropoly/qMRLab/src','-cover_json_file','coverage_SimTest_qmt_sirfse.json');exit(~res);"
  - stage: Test
    script: travis_wait 30 octave --no-gui --eval "bootstrapTest;cd('/home/travis/build/neuropoly/qMRLab/Test/MoxUnitCompatible');res=moxunit_runtests('SimTest_qmt_spgr.m');exit(~res);"
  - stage: Test
    script: travis_wait 30 octave --no-gui --eval "bootstrapTest;cd('/home/travis/build/neuropoly/qMRLab/Test/MoxUnitCompatible');res=moxunit_runtests('SimTest_inversion_recovery.m','-with_coverage','-cover','/home/travis/build/neuropoly/qMRLab/src','-cover_json_file','coverage_SimTest_inversion_recovery.json');exit(~res);"
  - stage: Test
    script: travis_wait 30 octave --no-gui --eval "bootstrapTest;cd('/home/travis/build/neuropoly/qMRLab/Test/MoxUnitCompatible');res=moxunit_runtests('SimTest_vfa_t1.m','-with_coverage','-cover','/home/travis/build/neuropoly/qMRLab/src','-cover_json_file','coverage_SimTest_vfa_t1.json');exit(~res);"
  - stage: Test
    script: travis_wait 30 octave --no-gui --eval "bootstrapTest;cd('/home/travis/build/neuropoly/qMRLab/Test/MoxUnitCompatible');res=moxunit_runtests('SimTest_mwf.m','-with_coverage','-cover','/home/travis/build/neuropoly/qMRLab/src','-cover_json_file','coverage_SimTest_mwf.json');exit(~res);"
  - stage: CombineReports
    script: ls ~/$TRAVIS_BUILD_NUMBER/;ls s3://qmrlab/$TRAVIS_BUILD_NUMBER;cp ~/$TRAVIS_BUILD_NUMBER/*.json /home/travis/build/neuropoly/qMRLab/Test/MoxUnitCompatible/;octave --no-gui --eval "cd('/home/travis/build/neuropoly/qMRLab/');startup;mocov_combine('/home/travis/build/neuropoly/qMRLab/Test/MoxUnitCompatible/','coverage_combined.json')";cp /home/travis/build/neuropoly/qMRLab/Test/MoxUnitCompatible/coverage_combined.json ~/$TRAVIS_BUILD_NUMBER/
  - stage: Coveralls
    script: ls ~/$TRAVIS_BUILD_NUMBER/;ls s3://qmrlab/$TRAVIS_BUILD_NUMBER;cp ~/$TRAVIS_BUILD_NUMBER/coverage_combined.json /home/travis/build/neuropoly/qMRLab/Test/MoxUnitCompatible/;curl --verbose -F json_file=@/home/travis/build/neuropoly/qMRLab/Test/MoxUnitCompatible/coverage_combined.json https://coveralls.io/api/v1/jobs