jobs:
- job: Ubuntu_R2020b
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
    - checkout: self
      fetchDepth: 1
    - task: InstallMATLAB@0
    - task: RunMATLABCommand@0
      displayName: Run qMRLab
      inputs:
        command: |
          init_qmrlab;
          qMRLabVer;
          tic;
          res1=moxunit_runtests([getenv('BUILD_REPOSITORY_LOCALPATH') '/Test/MoxUnitCompatible/quickMoxTests'],'-recursive');
          res2=moxunit_runtests([getenv('BUILD_REPOSITORY_LOCALPATH') '/Test/MoxUnitCompatible/BatchExample_test.m']);
          toc;
          exit(~all([res1 res2]));