jobs:
- job: Ubuntu_R2020b
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
    - checkout: self
      fetchDepth: 1
    - task: InstallMATLAB@0
    - task: RunMATLABCommand@0
      displayName: Run qMRLab
      inputs:
        command: |
          setenv('ISAZURE','1');
          blddir = getenv('BUILD_REPOSITORY_LOCALPATH');
          disp(blddir);
          startup;
          qMRLabVer;
          cd('Test/MoxUnitCompatible/quickMoxTests');
          res=moxunit_runtests(pwd,'-recursive');
          exit(~res);