jobs:
- job: Ubuntu_R2020b
  pool:
    vmImage: 'Ubuntu-20.04'
  steps:
    - checkout: self
      fetchDepth: 1
    - task: InstallMATLAB@0
      displayName: Install MATLAB R2020b
      inputs:
        release: R2020b
    - task: RunMATLABCommand@0
      displayName: Run qMRLab
      inputs:
        command: |
          exp = getenv('SYSTEM_DEFAULTWORKINGDIRECTORY');
          act = pwd;
          ls;
          startup; 
          assert(strcmp(act, exp), strjoin({act exp}, '\n'));
          disp('Test Done');
          exit;