jobs:
- job: Ubuntu R2020b
  pool:
    vmImage: 'Ubuntu 20.04'
  steps:
    - checkout: none
    - task: InstallMATLAB@0
      displayName: Install MATLAB R2020b
      inputs:
        release: R2020b
    - task: RunMATLABCommand@0
      displayName: Run matlab Ubuntu
      inputs:
        command: |
          exp = getenv('SYSTEM_DEFAULTWORKINGDIRECTORY');
          act = pwd; 
          assert(strcmp(act, exp), strjoin({act exp}, '\n'));
          disp('Test Done');
          exit;
- job: Catalina R2020a
  pool:
    vmImage: 'macOS-latest'
  steps:
    - checkout: none
    - task: InstallMATLAB@0
      displayName: Install MATLAB R2020a
      inputs:
        release: R2020a
    - task: RunMATLABCommand@0
      displayName: Run matlab OSX
      inputs:
        command: |
          exp = getenv('SYSTEM_DEFAULTWORKINGDIRECTORY');
          act = pwd; 
          disp(exp);
          disp(act);
          disp('Test Done');
          exit;