jobs:
- job: qMRLab_Test_Job1
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
    - checkout: self
      fetchDepth: 1
    - task: InstallMATLAB@0
    - task: RunMATLABCommand@0
      displayName: quickMox_and_BatchExample
      inputs:
        command: |
          init_qmrlab;
          qMRLabVer;
          qmrlabRoot = getenv('BUILD_REPOSITORY_LOCALPATH');
          res0=moxunit_runtests([qmrlabRoot '/External/MOcov/tests']);
          res1=moxunit_runtests([qmrlabRoot '/Test/MoxUnitCompatible/quickMoxTests'],'-recursive','-with_coverage','-cover',[qmrlabRoot '/src'],'-cover_exclude','*GUI*','-cover_json_file','coverage_quickMoxTests.json');
          exit(~all([res0 res1]));
    - script: |
        bash <(curl -s https://codecov.io/bash) -f "$BUILD_REPOSITORY_LOCALPATH/Test/MoxUnitCompatible/quickMoxTests/coverage_quickMoxTests.json" -F misc
      displayName: 'Upload to Codecov.io'