jobs:
- job: qMRLab_Test_Job1
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
    - checkout: self
      fetchDepth: 1
    - task: InstallMATLAB@0
    - task: RunMATLABCommand@0
      displayName: quickMox_and_BatchExample
      inputs:
        command: |
          init_qmrlab;
          qMRLabVer;
          qmrlabRoot = getenv('BUILD_REPOSITORY_LOCALPATH');
          testDir = '/Test/MoxUnitCompatible/quickMoxTests'
          res1=moxunit_runtests([qmrlabRoot testDir],'-recursive','-with_coverage','-cover',[qmrlabRoot '/src'],'-cover_exclude','*GUI*','-cover_json_file',[qmrlabRoot testDir '/coverage_quickMoxTests.json']);
          ls([[qmrlabRoot testDir]]);
          exit(~res1);
    - script: |
        bash <(curl -s https://codecov.io/bash) -f "$BUILD_REPOSITORY_LOCALPATH/Test/MoxUnitCompatible/quickMoxTests/coverage_quickMoxTests.json" -F matlab
      displayName: 'Upload to Codecov.io'
jobs:
- job: parpool_test
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
    - task: InstallMATLAB@0
    - task: RunMATLABCommand@0
      displayName: parpool
      inputs:
        command: |
          parpool(2);
          parfor ii=1:4
            b = get(getCurrentTask(),'ID');
            display(b)
          end