jobs:
- job: Ubuntu_R2020b
  pool:
    vmImage: 'Ubuntu-20.04'
  steps:
    - checkout: self
      fetchDepth: 1
    - task: InstallMATLAB@0
      displayName: Install MATLAB R2020b
      inputs:
        release: R2020b
    - task: RunMATLABCommand@0
      displayName: Run qMRLab
      inputs:
        command: |
          setenv('ISAZURE','1');
          act = pwd;
          ls;
          startup;
          qMRLabVer;
          disp('Test Done');
          exit;